// Generated by CoffeeScript 1.7.1
(function() {
  var app, gem;

  app = angular.module('myApp', []);

  app.controller('myController', function() {
    this.product = gem;
    return 0;
  });

  gem = {
    name: "kobe"
  };

}).call(this);
