// Generated by CoffeeScript 1.7.1
(function() {
  var mainApp;

  mainApp = angular.module('mainApp', ['ngRoute', 'mainCtrl']);

  mainApp.config([
    '$routeProvider', function($routeProvider) {
      $routeProvider.when('/product/list', {
        templateUrl: 'Content/product_list.html',
        controller: 'ProductListCtrl'
      }).when('/product/:productId/detail', {
        templateUrl: 'Content/product_detail.html',
        controller: 'ProductDetailCtrl'
      }).otherwise({
        redirectTo: '/'
      });
      return 0;
    }
  ]);

}).call(this);
