// Generated by CoffeeScript 1.7.1
(function() {
  var mainCtls;

  mainCtls = angular.module('mainCtls', []);

  mainCtls.controller('MainCtl', function($scope, $http) {
    $scope.title = "Web project";
    return 0;
  });

  mainCtls.controller('ProductListCtl', function($scope, Product) {
    return $scope.products = Product.query();
  });

  mainCtls.controller('ProductDetailCtl', function($scope, $routeParams, Product) {
    return $scope.product = Product.get({
      productId: $routeParams.productId
    });
  });

  mainCtls.controller('UserListCtl', function($scope, User) {
    return $scope.users = User.query();
  });

  mainCtls.controller('UserDetailCtl', function($scope, $routeParams, User) {
    return $scope.user = User.get({
      userId: $routeParams.userId
    });
  });

}).call(this);
