// Generated by CoffeeScript 1.7.1
(function() {
  var mainCtls;

  mainCtls = angular.module('mainCtls', []);

  mainCtls.controller('MainCtl', function($scope, $http) {
    $scope.title = "Web project";
    return 0;
  });

  mainCtls.controller('ProductListCtl', function($scope, Product) {
    return $scope.product_list = Product.query();
  });

  mainCtls.controller('ProductDetailCtl', function($scope, $routeParams, Product) {
    return $scope.product = Product.get({
      productId: $routeParams.productId,
      action: 'detail'
    });
  });

}).call(this);
