// Generated by CoffeeScript 1.7.1
(function() {
  var mainCtls;

  mainCtls = angular.module('mainCtls', []);

  mainCtls.controller('MainCtl', function($scope, $http) {
    return $scope.title = 'Web project';
  });

  mainCtls.controller('UserListCtl', function($scope, User) {
    $scope.users = User.query();
    return $scope.headers = ['email', 'first_name', 'last_name'];
  });

  mainCtls.controller('UserDetailCtl', function($scope, $routeParams, User) {
    return $scope.user = User.get({
      userId: $routeParams.userId,
      action: 'index'
    });
  });

  mainCtls.controller('ProductListCtl', function($scope, Product) {
    $scope.products = Product.query();
    return $scope.headers = ['name'];
  });

  mainCtls.controller('ProductDetailCtl', function($scope, $routeParams, Product) {
    return $scope.product = Product.get({
      productId: $routeParams.productId,
      action: 'index'
    });
  });

}).call(this);
